" My vimrc file
"
" Maintainer:	Simon Xu<xixu@paypal.com>
" Last change:	2010 Jul 31

" general
set number
set showcmd
set hidden
set autochdir
set incsearch
set hlsearch
set nobackup
set showmatch
set wildmenu
set ignorecase
set infercase
set notextmode
set autoread
set backspace=indent,eol,start
syntax on
map <space> <c-f>

" look and feel
" gui
if has("gui_running")
	set mouse=a
	set go=cegrLtbm
	let $lang = "en_US"
	set langmenu=en_US
	source $VIMRUNTIME/delmenu.vim
	source $VIMRUNTIME/menu.vim
	set laststatus=2
	set statusline=%<%F%h%m%r%h%w%y\ %=\|%{&ff}\|Ln:\ %l\ Col:\ %c
else
	let &t_Co=256
	"colorscheme slate
endif

set cursorline
hi Cursorline cterm=NONE ctermbg=lightgrey guibg=lightcyan
set cursorcolumn
hi Cursorcolumn cterm=NONE ctermbg=lightgrey guibg=lightcyan
hi Search cterm=NONE ctermbg=lightblue

" text format
if has("win32")
	set gfn=Consolas:h11:cANSI
else
    set gfn=Consolas\ 11
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

else

  set autoindent        " always set autoindenting on

endif " has("autocmd")

set nowrap
set tabstop=4
set shiftwidth=4
set smartindent
set expandtab

" spell check
set spelllang=en
set spellsuggest=5

" autocomplete
set complete=.,t,d,i
set completeopt=menu,menuone

" ctags
let Tlist_Show_One_file = 1
let Tlist_Exit_OnlyWindow = 1
let Tlist_Use_SingleClick = 1
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_Process_File_Always = 0
map <F9> :!ctags -R<cr>
map <F2> :TlistToggle<cr>
